# Generated by Django 2.2.1 on 2019-05-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ip_like',
            field=models.ManyToManyField(blank=True, to='blog.IpUser', verbose_name='Кто лайкнул (IP)'),
        ),
    ]
