# Generated by Django 2.2.1 on 2019-05-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Название'),
        ),
    ]
