# Generated by Django 2.2.1 on 2019-05-23 15:38

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20190518_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
